services:
  postgres:
    image: 'postgres:17'
    container_name: 'postgres-db'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: moviego
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    ports:
      - '5432:5432'
    #profiles:
    #  - dev   docker compose --profile 'dev' up
    pull_policy: never
    stop_grace_period: 10s


volumes:
  postgres-data:
    name: postgres-data
    labels:
      com.healthsync.description: "PostgreSQL data volume"
      com.healthsync.dev.mode: "development"

networks:
  postgres-network:
    name: postgres-network