spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
  config:
    import: optional:file:.env[.properties]
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 100MB

  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        base-link: ${AWS_BASE_LINK}
        bucket:
          name: ${AWS_BUCKET_NAME}

  threads:
    virtual:
      enabled: true
security:
  remember-me:
    key: ${REMEMBER_ME_KEY}

