spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5400/moviego
    password: postgres
    username: postgres
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      pool-name: MovieGOHikariPool
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 9090
  tomcat:
    max-http-form-post-size: 10MB
    uri-encoding: UTF-8