spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
  config:
    import: optional:file:.env[.properties]
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: public
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 100MB
  cache:
    type: redis
    redis:
      time-to-live: 2h
      cache-null-values: false
  data:
    redis:
      port: 6379
      host: localhost
      timeout: 5000
      repositories:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  mail:
    username: moviego.team@gmail.com
    password: 'blxa jzkb wpvy mhzm'
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        base-link: ${AWS_BASE_LINK}
        bucket:
          name: ${AWS_BUCKET_NAME}
  threads:
    virtual:
      enabled: true

rabbitmq:
  queue: notification.mail
  exchange: notification-events
  routing-key: mail.sent

security:
  remember-me:
    key: ${REMEMBER_ME_KEY}

