spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        base-link: ${AWS_BASE_LINK}
        bucket:
          name: ${AWS_BUCKET_NAME}

